### ISSUE TITLE
Get "servicePrincipals": unsupported protocol scheme

### ISSUE THREAD

**Issue by ronsun8** [microsoftgraph/msgraph-beta-sdk-go#52]
I upgraded msgraph-beta-sdk-go to 0.11.0 and get 
`Get "servicePrincipals": unsupported protocol scheme`

when using 
`	result, err := client.ServicePrincipals().Get(nil)
`and
`	result, err = serviceprincipals.NewServicePrincipalsRequestBuilder(*result.GetNextLink(), adapter).Get(nil)
`
I am using the beta gov cloud
`	adapter.SetBaseUrl("https://graph.microsoft.us/beta")
`

version 0.5.0 did not have this problem and works great

**Comment by baywet** [comment]
Hi @ronsun8 ,
Thanks for reaching out and for trying the go sdk.
Are you able to narrow down which version it stopped working?
Installing specific versions with `@version` at the end of the package name should allow you to try specific versions

**Comment by baywet** [comment]
Sorry, I missed the fact that you were trying to iterate over paged collections. What might be happening is the application reached the end of the collection, so the next link is empty (as expected by OData standards), which issues an invalid request.

Since the earlier version you were using, we've released support for Page Iterator, which automatically iterates over collections for you.

You can use it this way 

```Golang

result, err := client.ServicePrincipals().Get(nil)
if err != nil {
    fmt.Printf("Error service principals: %v\n", err)
    return err
}

// Use PageIterator to iterate through all service principals
pageIterator, err := msgraphcore.NewPageIterator(result, requestAdapter,
    func() serialization.Parsable {
        return abstractionsSerialization.Parsable { return servicePrincipals.NewServicePrincipalsResponse() }
    })

err = pageIterator.Iterate(func(pageItem interface{}) bool {
    servicePrincipal := pageItem.(*graph.ServicePrincipal)
    // do something with the value
    // Return true to continue the iteration
    return true
})
```

where:
- abstractionsSerialization is an import alias for `github.com/microsoft/kiota/abstractions/go/serialization`
- servicePrincipals is an import alias for `github.com/microsoftgraph/msgraph-beta-sdk-go/serviceprincipals`
- graph is an import alias for `github.com/microsoftgraph/msgraph-beta-sdk-go/models/microsoft/graph` 
- msgraphcore is an import alias for `github.com/microsoftgraph/msgraph-sdk-go-core` 
- requestAdapter is the request adapter you created for the client.
