### ISSUE TITLE
missing support for synchronization secrets

### ISSUE THREAD

**Issue by dhohengassner** [microsoftgraph/msgraph-beta-sdk-go#54]
I am trying to use the SDK to replace my curl commands. I do need to create a synchronization secret:
https://docs.microsoft.com/en-us/graph/api/synchronization-synchronization-secrets

It seems to me support for this call is missing:  

I am also not sure how to create a PR here - it seems the code is generated.

All suggestions and help is appreciated!
Thanks

**Comment by baywet** [comment]
Hi @dhohengassner 
Thanks for trying the Go SDK and for reporting this.
You are right, this path item is missing from the SDK, and the SDK is generated.

Here is a high level overview of the process API go through to make their way in the SDK.

1. service owners (workloads) describe their APIs in [CSDL](https://github.com/microsoftgraph/msgraph-metadata/tree/master/clean_beta_metadata), the file gets updated weekly.
2. pipelines use [OpenAPI.OData](https://github.com/microsoft/OpenAPI.NET.OData) to convert this description into an OpenAPI description
3. pipelines use [Kiota](https://github.com/microsoft/kiota) to use the OpenAPI description and generate an SDK update pull request.
4. the team merges and releases the PR.

The first issue was that the conversion library was not adding those path items, this has been addressed through [this](https://github.com/microsoft/OpenAPI.NET.OData/pull/158) and [that](https://github.com/microsoft/OpenAPI.NET.OData/pull/180) PRs.

Then the issue was fixed, but we didn't have a version of the conversion library we could use in the pipelines, [it's now available as a preview](https://www.nuget.org/packages/Microsoft.OpenApi.OData/1.0.10-preview1).

Now the generation pipelines need to be updated to leverage that new version, I'd already put [this](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/694) and [that](https://github.com/microsoftgraph/msgraph-metadata/pull/117) PRs together.

However, those PRs are blocked on a new tool, [hidi](https://www.nuget.org/packages/Microsoft.OpenApi.Hidi), to be released, we have engineers working on fixing that as we speak.

Then the next step will be to insert a a restriction annotation in the metadata to enable that path item, since it won't be added by default (this behavior is opt-in rather than opt-out). (on the secrets property of the synchronization type).
If you feel like contributing, and if you're comfortable with XSLT, we'd gladly accept a pull request for that. [you can look at this example](https://github.com/microsoftgraph/msgraph-metadata/blob/da4958302b55f684efeaac0b2bb8c7ddaf8c6abe/transforms/csdl/preprocess_csdl.xsl#L537), the main differences being the target and the fact that it'll be an update restriction instead of a read restriction.

Lastly, after all those changes, we'll need to wait for another weekly generation pull request.

I hope this clarifies the process. Don't hesitate if you have follow up questions.

**Comment by baywet** [comment]
update: we've just released a new version that solves using request builders with raw urls and takes advantage of the new metadata generation pipeline.

now, all what's missing is the annotation to augment the metadata during the conversion, I've [logged an issue to track this](https://github.com/microsoftgraph/msgraph-metadata/issues/127) in the metadata repo.

you can update by running the follow command

```bash
go get -u github.com/microsoftgraph/msgraph-beta-sdk-go@v0.14.0
```

**Comment by baywet** [comment]
Hi everyone,
Thanks for the patience on this. The metadata issue was fixed earlier today.
After another generation and release (should happen tomorrow), this should be fixed.

**Comment by baywet** [comment]
Update on this.
We haven't been able to release beta for a month now due to issues in the metadata and other priorities.
We're working to get this unblock and this fix will be part of the next release.

**Comment by baywet** [comment]
Apologies, I forgot to update this issue. The method [is now available](https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/d36374dbd03935ba4c086d700cd7653c3facf47e/serviceprincipals/item_synchronization_secrets_request_builder.go#L40)

```Go
graphClient.ServicePrincipalsById("servicePrincipal-id").Synchronization().Secrets().Put(context.Background(), requestBody, nil)
```

Closing.
